[tools]
helix = "latest"
"pipx:ruff" = "latest"
"pipx:ty" = "latest"
sqlite = "latest"
uv = "latest"

[tasks.lint]
run = "ruff check"

[tasks.typecheck]
run = "ty check"

[tasks.test]
run = "uv run pytest"

[tasks.build]
run = "uv build"

[tasks.generate-docs]
run = "uv run typer budy utils docs --output README.md --name budy"

[tasks.ci]
depends = [
  "lint",
  "typecheck",
  # "test",
  "build",
  "generate-docs",
]
